spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      password: bdung
      username: mongoadmin
      authentication-database: admin

  mail:
    host: smtp.mail.ru
    port: 465
    username: robot@goeasy.space
    password: CaMye4wcmaWWVpK7Dt0w
    properties:
      "mail.smtp.ssl.enable": true
      "mail.auth": true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port:
    8090