spring:
  application:
    name: user-service
  data:
    mongodb:
      host: rs01/rc1a-iaj8kf6jaomgk9lf.mdb.yandexcloud.net
      port: 27018
      password: goeasyuser
      username: user-service
      authentication-database: user-service

  mail:
    host: smtp.mail.ru
    port: 465
    username: robot@goeasy.space
    password: CaMye4wcmaWWVpK7Dt0w
    properties:
      "mail.smtp.ssl.enable": true
      "mail.auth": true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port:
    8090